/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MatchImport } from './routes/match'
import { Route as IndexImport } from './routes/index'
import { Route as MasteryIndexImport } from './routes/mastery/index'

// Create/Update Routes

const MatchRoute = MatchImport.update({
  path: '/match',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const MasteryIndexRoute = MasteryIndexImport.update({
  path: '/mastery/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/match': {
      preLoaderRoute: typeof MatchImport
      parentRoute: typeof rootRoute
    }
    '/mastery/': {
      preLoaderRoute: typeof MasteryIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  MatchRoute,
  MasteryIndexRoute,
])

/* prettier-ignore-end */
